`timescale 1ns / 1ps
//
// mod_v2_encrypt_192 — timing-optimised two-stage pipelined AES-192 encrypt
//
// Pipeline split
// --------------
//   Stage 1 (S_ROUND_S1): SubBytes → ShiftRows            → register sr_pipe / rk_pipe
//   Stage 2 (S_ROUND_S2): MixColumns(sr_pipe) ^ rk_pipe   → state_reg
//
// This limits each stage to ≈ 8.5 ns (well within 10 ns at 100 MHz) compared
// with the original single-cycle path of ≈ 12–14 ns.
//
// Key expansion
// -------------
// aes_key_expand_192_seq is instantiated here and produces all 13 round keys
// over 9 clock cycles after a key_load pulse.  key_load fires for exactly one
// cycle (combinationally) whenever start is asserted while the FSM is idle.
//
// Latency
// -------
//   9 (key expand) + 1 (initial ARK) + 11×2 (rounds 1–11) + 2 (final round)
//   + 1 (S_DONE) = 35 cycles ≈ 350 ns at 100 MHz.
//   At UART speeds this overhead is completely negligible.
//
// External interface is UNCHANGED — drop-in replacement for the original.

module mod_v2_encrypt_192 (
    input              clk,
    input              rst,
    input  [127:0]     plaintext,
    input  [191:0]     key,
    input              start,
    output reg [127:0] ciphertext,
    output reg         done
);

localparam Nr = 12;

// -----------------------------------------------------------------------
// FSM state encoding
// -----------------------------------------------------------------------
localparam [2:0]
    S_IDLE     = 3'd0,
    S_KEY_WAIT = 3'd1,
    S_ROUND_S1 = 3'd2,
    S_ROUND_S2 = 3'd3,
    S_LAST_ARK = 3'd4,
    S_DONE     = 3'd5;
reg [2:0] fsm;

// -----------------------------------------------------------------------
// Sequential key expansion
// key_load_r is a REGISTERED one-cycle pulse generated by the FSM at the
// same posedge that transitions S_IDLE→S_KEY_WAIT.  A registered signal
// is used (rather than a combinatorial wire from `start`) to avoid a
// simulation race condition where the testbench's blocking `start = 0`
// could execute between the FSM's always block and the key-expander's
// always block within the same time step.
// -----------------------------------------------------------------------
wire [1663:0] round_keys_flat;
wire          rk_valid;
reg           key_load_r;

aes_key_expand_192_seq u_kexp (
    .clk            (clk),
    .rst            (rst),
    .key_in         (key),
    .key_load       (key_load_r),
    .round_keys_flat(round_keys_flat),
    .valid          (rk_valid)
);

// -----------------------------------------------------------------------
// Round key extraction from the flat bus
// -----------------------------------------------------------------------
function [127:0] get_rk;
    input [3:0] n;
    get_rk = round_keys_flat[1663 - 128*n -: 128];
endfunction

// -----------------------------------------------------------------------
// Datapath registers
// -----------------------------------------------------------------------
reg [127:0] state_reg;
reg [3:0]   round_cnt;
reg [127:0] sr_pipe;   // Stage-1 output: ShiftRows result
reg [127:0] rk_pipe;   // Stage-1 output: round key for Stage-2 ARK

// -----------------------------------------------------------------------
// Stage-1 combinatorial path  (SubBytes → ShiftRows)
// Critical path: rk mux (~2 ns) → xorkey (~1 ns) → S-box (~5.5 ns) ≈ 8.5 ns
// -----------------------------------------------------------------------
wire [127:0] rk_for_sb = get_rk(round_cnt);
wire [127:0] sb_out, sr_out;

mod_v2_sub_bytes u_sb (
    .data_in  (state_reg),
    .round_key(rk_for_sb),
    .data_out (sb_out)
);
aes_shift_rows u_sr (
    .data_in (sb_out),
    .data_out(sr_out)
);

// -----------------------------------------------------------------------
// Stage-2 combinatorial path  (MixColumns)
// Critical path: MixColumns (~3.5 ns) ≈ 4 ns — comfortable
// -----------------------------------------------------------------------
wire [127:0] mc_out;
aes_mix_columns u_mc (
    .data_in (sr_pipe),
    .data_out(mc_out)
);

// -----------------------------------------------------------------------
// FSM
// -----------------------------------------------------------------------
always @(posedge clk or posedge rst) begin
    if (rst) begin
        fsm       <= S_IDLE;
        done      <= 1'b0;
        round_cnt <= 4'd0;
        state_reg <= 128'd0;
        ciphertext<= 128'd0;
        sr_pipe   <= 128'd0;
        rk_pipe   <= 128'd0;
        key_load_r<= 1'b0;
    end else begin
        done       <= 1'b0;   // default; overridden in S_DONE
        key_load_r <= 1'b0;   // default; pulsed only in S_IDLE when start
        case (fsm)

            // Trigger key expansion and advance to wait state.
            S_IDLE: if (start) begin
                key_load_r <= 1'b1;   // registered pulse, race-free
                fsm        <= S_KEY_WAIT;
            end

            // Wait 9 cycles for key expansion to complete.
            S_KEY_WAIT: if (rk_valid) begin
                state_reg <= plaintext ^ get_rk(4'd0);  // initial AddRoundKey
                round_cnt <= 4'd1;
                fsm       <= S_ROUND_S1;
            end

            // Stage 1: SubBytes(state_reg) → ShiftRows → sr_pipe
            //          Latch round key for Stage 2.
            S_ROUND_S1: begin
                sr_pipe <= sr_out;
                rk_pipe <= get_rk(round_cnt);
                fsm     <= (round_cnt == Nr[3:0]) ? S_LAST_ARK : S_ROUND_S2;
            end

            // Stage 2: MixColumns(sr_pipe) ^ rk_pipe → state_reg
            S_ROUND_S2: begin
                state_reg <= mc_out ^ rk_pipe;
                round_cnt <= round_cnt + 4'd1;
                fsm       <= S_ROUND_S1;
            end

            // Final round: AddRoundKey only (no MixColumns)
            S_LAST_ARK: begin
                ciphertext <= sr_pipe ^ rk_pipe;
                state_reg  <= sr_pipe ^ rk_pipe;
                fsm        <= S_DONE;
            end

            S_DONE: begin
                done <= 1'b1;
                fsm  <= S_IDLE;
            end

            default: fsm <= S_IDLE;
        endcase
    end
end

endmodule
